{
 "title": "MongoDB Monitoring",
 "tags": [
  "monitoring",
  "mongo"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Mongo Ops/sec",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 10 },
   "targets": [
    {
     "expr": "sum by (rs_nm) (increase(mongodb_ss_opcounters[1m])) / 60"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum by (instance) (mongodb_ss_connections{conn_type=\"active\"})"
    }
   ]
  },
  {
   "title": "Cache hit %",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "(rate(mongodb_ss_wt_cache_pages_requested_from_the_cache[5m])-rate(mongodb_ss_wt_cache_pages_read_into_cache[5m]))/rate(mongodb_ss_wt_cache_pages_requested_from_the_cache[5m])* 100"
    }
   ]
  },
  {
   "title": "Global lock queue",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 10, "w": 8, "h": 10 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_wt_lock_txn_global_lock_application_thread_time_waiting_usecs[5m])"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 10, "w": 10, "h": 12 },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=~\"(?i).*mongo.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 20, "w": 12, "h": 16 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"(?i).*mongo.*\"}"
    }
   ]
  },
  {
   "title": "Replica role",
   "type": "timeseries",
   "gridPos": { "x": 10, "y": 12, "w": 10, "h": 8 },
   "targets": [
    { "expr": "mongodb_rs_members_state" }
   ]
  }
 ]
}